#!/bin/bash
FILE1=/path/to/audio/file1
FILE2=/path/to/audio/file2
FILE3=/path/to/audio/file3
FILE4=/path/to/audio/file4
FILE5=/path/to/audio/file5
while [[ 1 ]]; do
	echo $FILE1 > mixer
	echo $FILE2 > mixer
	echo $FILE3 > mixer
	echo $FILE4 > mixer
	echo $FILE5 > mixer
	sleep 0.5
done
